import {expect, it} from 'vitest';
import {lint} from '../linter/index.js';
import {parseCartography} from '../parser/parse.js';
const doc = (yaml = '', prose = '## Overview\n\nText.') => `---\nversion: "0.3.0"\nname: Test\n${yaml}---\n\n${prose}`;
const passes = (yaml = '', prose?: string) => expect(lint(doc(yaml, prose)).summary.errors).toBe(0);
const rejects = (yaml: string, rule: string) => expect(lint(doc(yaml)).findings.some((finding) => finding.ruleId === rule)).toBe(true);
it('V01 accepts the minimal valid file', () => passes());
it('V02 accepts group aliases', () => passes('colors:\n  ink: "#111111"\n  alias: "{colors.ink}"\n'));
it('V03 accepts a valid dash pattern', () => passes('dashes:\n  road: [4px, 2px]\n'));
it('V04 rejects invalid token identifiers', () => rejects('colors:\n  中文: "#111111"\n', 'schema'));
it('V05 rejects unquoted YAML token references', () => rejects('colors:\n  ink: "#111111"\n  alias: {colors.ink}\n', 'yaml-reference-unquoted'));
it('V06 rejects unquoted hex colors', () => rejects('colors:\n  ink: #111111\n', 'yaml-hex-color-unquoted'));
it('V07 rejects malformed omitted objects', () => rejects('omitted:\n  - reason: no\n', 'schema'));
it('V08 rejects duplicate omitted aliases', () => rejects('omitted: [Colors, 色彩]\n', 'omitted-sections'));
it('V09 rejects body and omitted conflict', () => rejects('omitted: [Overview]\n', 'omitted-sections'));
it('V10 requires a core element style', () => rejects('elements:\n  road:\n    geometry: line\n', 'schema'));
it('V11 rejects zero dash members', () => rejects('dashes:\n  road: [4px, 0px]\n', 'schema'));
it('V11 rejects odd dash patterns', () => rejects('dashes:\n  road: [4px, 2px, 1px]\n', 'dash-pattern'));
it('V11 rejects mixed dash units', () => rejects('dashes:\n  road: [4px, 2mm]\n', 'dash-pattern'));
it('V12 rejects broken references', () => rejects('colors:\n  ink: "{colors.none}"\n', 'token-reference'));
it('V13 normalizes fullwidth headings', () => expect(parseCartography(doc('', '## Ｃｏｌｏｒｓ\n\nText.')).sections[0]?.canonicalHeading).toBe('Colors'));
it('V14 rejects duplicate aliases', () => expect(lint(doc('', '## Colors\n\nA\n\n## 色彩\n\nB')).findings.some((finding) => finding.ruleId === 'duplicate-section')).toBe(true));
it('V15 warns for section order', () => { const report = lint(doc('', '## Colors\n\nA\n\n## Overview\n\nB')); expect(report.valid).toBe(true); expect(report.findings.some((finding) => finding.ruleId === 'section-order')).toBe(true); });
it('V16 rejects renderer bindings', () => rejects('elements:\n  road:\n    geometry: line\n    strokeWidth: 1px\n    paint: x\n', 'element-reserved-property'));
it('V17 preserves unknown fields', () => passes('custom: value\n'));
it('V18 ignores escaped and code references', () => passes('', '## Overview\n\n\\{colors.none} and `{colors.none}`'));
it('V19 rejects non-string mapping keys', () => rejects('colors:\n  true: "#111111"\n', 'yaml-non-string-key'));
it('V20 rejects references in metadata', () => rejects('description: "{colors.ink}"\n', 'schema'));
it('V21 rejects currentColor', () => rejects('colors:\n  ink: currentColor\n', 'color-token'));
it('V22 rejects traversal through reference', () => rejects('custom:\n  a: "{custom.b}"\n  b: {c: value}\n  x: "{custom.a.c}"\n', 'token-reference'));
it('V23 ignores nested headings', () => expect(parseCartography(doc('', '> ## Colors\n\n- ## Colors\n\n    ## Colors')).sections).toHaveLength(0));
it('V23 ignores HTML, Setext, and fenced headings', () => expect(parseCartography(doc('', '<div>\n## Colors\n</div>\n\nColors\n---\n\n```md\n## Colors\n```')).sections).toHaveLength(0));
it('V24 accepts numeric token names', () => passes('widths:\n  "0": 1px\n  2xl: "{widths.0}"\n'));
it('V25 rejects negative zero dimensions', () => rejects('widths:\n  x: -0px\n', 'schema'));
it('V26 parses dates as strings', () => expect(parseCartography(doc('custom: 2026-08-31\n')).rawFrontmatter).toMatchObject({custom: '2026-08-31'}));
it('V27 rejects deep reference cycles', () => rejects('custom:\n  a:\n    inner: "{custom.b.inner}"\n  b:\n    inner: "{custom.a.inner}"\n', 'token-reference'));
it('V28 rejects normalized reserved keys', () => rejects('elements:\n  x:\n    geometry: line\n    strokeWidth: 1px\n    SourceLayer: x\n', 'element-reserved-property'));
it('V29 rejects blank omitted reasons', () => rejects('omitted:\n  - section: Colors\n    reason: "   "\n', 'schema'));
it('V30 rejects rem dimensions', () => rejects('widths:\n  x: 1rem\n', 'schema'));
it('V31 enforces exact enums', () => rejects('elements:\n  x:\n    geometry: Line\n    strokeWidth: 1px\n', 'schema'));
it('V32 checks resolved token use types', () => rejects('colors:\n  ink: "#111111"\nwidths:\n  x: "{colors.ink}"\n', 'known-token-type'));
it('V33 rejects metadata roots', () => rejects('colors:\n  ink: "{name.x}"\n', 'token-reference'));
it('V34 rejects YAML anchors', () => rejects('custom: &x value\n', 'yaml-alias-prohibited'));
it('V35 rejects whitespace names', () => rejects('name: "　"\n', 'schema'));
it('V36 accepts typography references', () => passes('typography:\n  a:\n    fontFamily: Arial\n    fontSize: 12px\n  b: "{typography.a}"\n'));
it('V37 rejects empty patterns', () => rejects('elements:\n  x:\n    geometry: polygon\n    pattern: []\n', 'schema'));
it('V38 rejects var colors', () => rejects('colors:\n  x: "rgb(var(--x))"\n', 'color-token'));
it('V39 rejects unknown-only element styles', () => rejects('elements:\n  x:\n    geometry: line\n    custom: x\n', 'schema'));
it('V40 accepts custom array references', () => passes('custom:\n  values: [x]\n  selected: "{custom.values[0]}"\n'));
it('V41 rejects blank mapping keys', () => rejects('"": x\n', 'yaml-non-string-key'));
it('V42 rejects references as keys', () => rejects('"{colors.ink}": x\n', 'reference-as-mapping-key'));
it('V43 rejects trailing newlines in dimensions', () => rejects('widths:\n  x: "1px\\n"\n', 'schema'));
