import type {RuleDescriptor} from '../model/types.js';

export const RULE_CATALOG: RuleDescriptor[] = [
  {id: 'frontmatter-required', severity: 'error', scope: 'document', description: 'Requires YAML frontmatter at the beginning of the file.'},
  {id: 'frontmatter-unclosed', severity: 'error', scope: 'document', description: 'Detects an unclosed YAML frontmatter fence.'},
  {id: 'yaml-syntax', severity: 'error', scope: 'document', description: 'Reports YAML parsing errors and duplicate keys.'},
  {id: 'yaml-alias-prohibited', severity: 'error', scope: 'document', description: 'Rejects YAML anchors and aliases.'},
  {id: 'yaml-custom-tag-prohibited', severity: 'error', scope: 'document', description: 'Rejects custom YAML tags.'},
  {id: 'yaml-merge-key-prohibited', severity: 'error', scope: 'document', description: 'Rejects YAML merge keys.'},
  {id: 'yaml-block-scalar-prohibited', severity: 'error', scope: 'document', description: 'Moves long prose out of YAML and into Markdown.'},
  {id: 'yaml-tab-indentation-prohibited', severity: 'error', scope: 'document', description: 'Rejects tab indentation in YAML.'},
  {id: 'yaml-non-finite-number-prohibited', severity: 'error', scope: 'document', description: 'Rejects non-finite YAML numbers at every front-matter depth.'},
  {id: 'schema', severity: 'error', scope: 'document', description: 'Validates the CARTOGRAPHY.md frontmatter schema.'},
  {id: 'duplicate-section', severity: 'error', scope: 'document', description: 'Rejects duplicate canonical Markdown sections.'},
  {id: 'document-size', severity: 'warning', scope: 'document', description: 'Warns when the contract is too large for reliable agent ingestion.'},
  {id: 'omitted-sections', severity: 'error', scope: 'document', description: 'Rejects unknown, duplicate, or present canonical section omissions.'},
  {id: 'required-sections', severity: 'warning', scope: 'document', description: 'Reports canonical narrative sections that are absent and not intentionally omitted.'},
  {id: 'empty-section', severity: 'warning', scope: 'document', description: 'Reports empty narrative sections.'},
  {id: 'section-order', severity: 'warning', scope: 'document', description: 'Checks the canonical order of Markdown sections.'},
  {id: 'unknown-root-key', severity: 'warning', scope: 'document', description: 'Preserves extensions while flagging likely misspellings.'},
  {id: 'token-reference', severity: 'error', scope: 'document', description: 'Checks exact `{path.to.token}` references and cycles.'},
  {id: 'color-token', severity: 'error', scope: 'document', description: 'Validates color tokens as generic CSS colors.'},
  {id: 'contrast-pairs', severity: 'error', scope: 'document', description: 'Checks declared color pairs against their WCAG 2.1 contrast minimum.'},
  {id: 'contract-summary', severity: 'info', scope: 'document', description: 'Summarizes loaded token leaves, token groups, and prose sections.'},
  {id: 'rule-execution', severity: 'error', scope: 'document', description: 'Contains unexpected validator-rule failures.'},
];
