import type {RuleDescriptor} from '../model/types.js';

export const RULE_CATALOG: RuleDescriptor[] = [
  {id: 'frontmatter-required', severity: 'error', scope: 'document', description: 'Requires YAML frontmatter at the beginning of the file.'},
  {id: 'frontmatter-unclosed', severity: 'error', scope: 'document', description: 'Detects an unclosed YAML frontmatter fence.'},
  {id: 'yaml-syntax', severity: 'error', scope: 'document', description: 'Reports YAML parsing errors and duplicate keys.'},
  {id: 'yaml-alias-prohibited', severity: 'error', scope: 'document', description: 'Rejects YAML anchors and aliases.'},
  {id: 'yaml-custom-tag-prohibited', severity: 'error', scope: 'document', description: 'Rejects custom YAML tags.'},
  {id: 'yaml-merge-key-prohibited', severity: 'error', scope: 'document', description: 'Rejects YAML merge keys.'},
  {id: 'yaml-block-scalar-prohibited', severity: 'error', scope: 'document', description: 'Moves long prose out of YAML and into Markdown.'},
  {id: 'yaml-tab-indentation-prohibited', severity: 'error', scope: 'document', description: 'Rejects tab indentation in YAML.'},
  {id: 'schema', severity: 'error', scope: 'document', description: 'Validates the CARTOGRAPHY.md frontmatter schema.'},
  {id: 'duplicate-section', severity: 'error', scope: 'document', description: 'Rejects duplicate canonical Markdown sections.'},
  {id: 'document-size', severity: 'warning', scope: 'document', description: 'Warns when the contract is too large for reliable agent ingestion.'},
  {id: 'required-sections', severity: 'warning', scope: 'document', description: 'Reports canonical narrative sections that are absent and not intentionally omitted.'},
  {id: 'empty-section', severity: 'warning', scope: 'document', description: 'Reports empty narrative sections.'},
  {id: 'section-order', severity: 'warning', scope: 'document', description: 'Checks the canonical order of Markdown sections.'},
  {id: 'unknown-root-key', severity: 'warning', scope: 'document', description: 'Preserves extensions while flagging likely misspellings.'},
  {id: 'token-reference', severity: 'error', scope: 'document', description: 'Checks exact `{path.to.token}` references and cycles.'},
  {id: 'color-token', severity: 'error', scope: 'document', description: 'Validates color token leaves with MapLibre’s color parser.'},
  {id: 'zoom-bands', severity: 'error', scope: 'document', description: 'Checks named zoom-band ranges and overlap.'},
  {id: 'layer-order', severity: 'error', scope: 'document', description: 'Checks semantic layer-group uniqueness and order.'},
  {id: 'scales', severity: 'error', scope: 'document', description: 'Checks categorical and numeric scale structure.'},
  {id: 'scale-fallback', severity: 'warning', scope: 'document', description: 'Requires explicit fallbacks for categorical scales.'},
  {id: 'encodings', severity: 'error', scope: 'document', description: 'Checks encoding rules, fields, scales, and zoom ranges.'},
  {id: 'unbound-semantic', severity: 'error', scope: 'document', description: 'Detects encoding fields that resolve to null semantic bindings.'},
  {id: 'channel-conflict', severity: 'warning', scope: 'document', description: 'Detects multiple semantic owners of a visual channel.'},
  {id: 'critical-secondary-channel', severity: 'error', scope: 'document', description: 'Requires redundant encoding for critical semantics when configured.'},
  {id: 'critical-color-only', severity: 'warning', scope: 'document', description: 'Warns when critical semantics rely only on color.'},
  {id: 'contrast-pairs', severity: 'error', scope: 'document', description: 'Checks declared static contrast pairs.'},
  {id: 'contract-summary', severity: 'info', scope: 'document', description: 'Summarizes tokens, scales, encodings, and layer groups.'},
  {id: 'validation-fixtures', severity: 'warning', scope: 'document', description: 'Checks declaration of representative render-review scenarios.'},
  {id: 'profile-file', severity: 'error', scope: 'profile', description: 'Reports companion profile file read failures.'},
  {id: 'profile-required', severity: 'error', scope: 'profile', description: 'Reports a missing DATA_PROFILE.json when required.'},
  {id: 'profile-schema', severity: 'error', scope: 'profile', description: 'Validates DATA_PROFILE.json structure.'},
  {id: 'profile-source', severity: 'error', scope: 'profile', description: 'Checks encoding source and source-layer declarations.'},
  {id: 'profile-geometry', severity: 'warning', scope: 'profile', description: 'Checks encoding geometry against profiled geometry.'},
  {id: 'profile-zoom', severity: 'warning', scope: 'profile', description: 'Checks encoding zoom availability against the profile.'},
  {id: 'profile-field', severity: 'error', scope: 'profile', description: 'Checks bound fields and label fallbacks against source-layer fields.'},
  {id: 'category-coverage', severity: 'warning', scope: 'profile', description: 'Checks categorical scale coverage against observed domains.'},
  {id: 'stable-feature-id', severity: 'warning', scope: 'profile', description: 'Requires stable feature identifiers for feature-state styling.'},
  {id: 'style-file', severity: 'error', scope: 'style', description: 'Reports companion style file read failures.'},
  {id: 'maplibre-style-spec', severity: 'error', scope: 'style', description: 'Runs the official MapLibre Style Specification validator.'},
  {id: 'style-metadata', severity: 'warning', scope: 'style', description: 'Checks Cartography.md traceability metadata on governed layers.'},
  {id: 'style-source-rule', severity: 'error', scope: 'style', description: 'Checks style layers against their declared encoding source rule.'},
  {id: 'style-token-ref', severity: 'error', scope: 'style', description: 'Checks token references embedded in layer metadata.'},
  {id: 'style-token-drift', severity: 'warning', scope: 'style', description: 'Detects literal style properties that drift from token bindings.'},
  {id: 'style-layer-order', severity: 'warning', scope: 'style', description: 'Checks governed layer group order in style.json.'},
  {id: 'style-stable-feature-id', severity: 'warning', scope: 'style', description: 'Requires stable profiled IDs for style layers that use feature-state.'},
  {id: 'style-portability', severity: 'warning', scope: 'style', description: 'Checks portable protocols and generated filter syntax.'},
  {id: 'deprecated-filter-syntax', severity: 'warning', scope: 'style', description: 'Warns about legacy property-filter syntax.'},
  {id: 'feature-state-paint-only', severity: 'error', scope: 'style', description: 'Restricts feature-state expressions to paint properties when configured.'},
  {id: 'rule-execution', severity: 'error', scope: 'document', description: 'Contains unexpected validator-rule failures.'},
];
